### ISSUE TITLE
Add flattrade broker support

### ISSUE THREAD

**Issue by coolpalani** [suresh-n/RichDotinScalperApp1#2]
The flattrade api is more stable than shoonya.
If you add a flattrade broker it would be great.

**Comment by suresh-n** [comment]
As of now its not possible , in future we try add multiple broker support.

**Comment by rahulmr** [comment]
@suresh-n we can have 2 releases one for Flattrade and another for Finvasia Shoonya - only the Login part differs. Eveything else is same. Endpoints need to be configured separately

**Comment by suresh-n** [comment]
@rahulmr I don't have account  flattradde account to test the things let me red the flattrade documentation and I will check the possibilities

**Comment by suresh-n** [comment]
Thanks for suggestions @rahulmr i was able to make the app work with Flattrade broker but seeing some small bug with websocket will fix that and will be releasing the exe sooner.

**Comment by suresh-n** [comment]
Added executable for Flattrade Api  in same release , https://github.com/suresh-n/RichDotinScalperApp1/releases/tag/v0.1.5
